name: Sync To Gitee

on: 
  push: 
    branches: [ main, develop, www ]
  delete:
    branches: [ main, develop, www ]
  create:
    branches: [ main, develop, www ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:BeyondDimension/SteamTools.git"
          destination-repo: "git@gitee.com:rmbgame/SteamTools"
